name: Run Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Openvpn
        env:
          OPENVPN_CLIENT_CONFIG: ${{ secrets.OPENVPN_CLIENT_CONFIG }}
        run: |
          sudo apt update
          sudo apt install openvpn
          echo $OPENVPN_CLIENT_CONFIG |base64 --decode > vlan.conf
          sudo openvpn --daemon --config vlan.conf
          